name: LRename
version: '1.0.0'
main: io.github.theeluke.LRename
api-version: '1.21'
authors: [theeluke]
description: Lightweight item renamer & lore editor
website: theeluke.github.io

softdepend: [Vault, PlaceholderAPI]

commands:
  lrename:
    description: "Main command for LRename"
    aliases: [lr]

permissions:
  lrename.use:
    description: "Allows basic access to LRename commands"
    default: op

  lrename.rename:
    description: "Allows renaming items"
    default: op
  lrename.lore:
    description: "Allows adding and removing lore lines"
    default: op
  lrename.copypaste:
    description: "Allows copying and pasting of item data"
    default: op
  lrename.clear:
    description: "Allows clearing names and lore entirely"
    default: op
  lrename.hide:
    description: "Allows hiding item flags like enchants and attributes"
    default: op
  lrename.templates:
    description: "Allows for saving item data."
    default: op
  lrename.admin:
    description: "Allows reloading the plugin configuration"
    default: op
  lrename.bypasscost:
    description: "Allows not having to pay if cost function is enabled."
    default: op
